// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqztfuokkrdnijgqjqiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxenRmdW9ra3JkbmlqZ3FqcWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTMxNDIsImV4cCI6MjA2NzM2OTE0Mn0.W1xgY1cyS1rtwyzmfOTloCqUCaMkox3z3TxjPSkRMv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});